# Generated by Django 4.1 on 2022-08-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='NewItem',
        ),
    ]
