# Generated by Django 4.1 on 2022-08-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmin', '0003_rename_newitem_newsitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='site',
            new_name='source',
        ),
    ]
