# Generated by Django 4.1 on 2022-11-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmin', '0004_rename_site_newsitem_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('headline', models.CharField(max_length=2550)),
                ('link', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
